import JobsPage, { Job } from '@/app/components/JobsPage'

const jobs: Job[] = [
  {
    id: 'ft-1',
    company: 'GoTo',
    position: 'Backend Engineer',
    location: 'Jakarta',
    salary: 'Rp 15–30 jt/bln',
    tags: ['Teknologi Informasi & Komunikasi'],
    description: 'GoTo Group membuka posisi Backend Engineer untuk bergabung dengan tim engineering yang membangun infrastruktur super app terbesar di Indonesia. Kamu akan bekerja pada sistem berskala besar dengan jutaan transaksi per hari.',
    requirements: [
      'Pengalaman minimal 3 tahun sebagai Backend Engineer',
      'Menguasai Go, Java, atau Python',
      'Pengalaman dengan microservices dan distributed systems',
      'Familiar dengan Kubernetes, Docker, dan cloud (GCP/AWS)',
      'Memahami database SQL dan NoSQL',
      'Pengalaman dengan message queue (Kafka/RabbitMQ)',
    ],
    benefits: [
      'Gaji kompetitif + equity',
      'Asuransi kesehatan premium untuk keluarga',
      'Flexible working arrangement',
      'Learning & development budget',
      'Saham perusahaan (ESOP)',
    ],
  },
  {
    id: 'ft-2',
    company: 'Sea Group',
    position: 'Product Manager',
    location: 'Jakarta',
    salary: 'Rp 20–40 jt/bln',
    tags: ['Teknologi Informasi & Komunikasi', 'CEO & Manajemen Umum'],
    description: 'Sea Group (Shopee, SeaMoney, Garena) mencari Product Manager berpengalaman untuk memimpin pengembangan produk di salah satu divisi bisnis kami yang berkembang pesat di Asia Tenggara.',
    requirements: [
      'Pengalaman minimal 4 tahun sebagai Product Manager di tech company',
      'Track record meluncurkan produk yang sukses',
      'Kemampuan analisis data yang kuat',
      'Pengalaman bekerja dengan tim engineering dan design',
      'Kemampuan komunikasi dan presentasi yang excellent',
      'Bahasa Inggris aktif',
    ],
    benefits: [
      'Paket kompensasi sangat kompetitif',
      'Asuransi kesehatan comprehensive',
      'Annual performance bonus',
      'Regional exposure dan kesempatan rotasi',
      'Lingkungan kerja internasional',
    ],
  },
  {
    id: 'ft-3',
    company: 'Astra',
    position: 'Data Scientist',
    location: 'Jakarta',
    salary: 'Rp 12–25 jt/bln',
    tags: ['Ilmu Pengetahuan & Teknologi', 'Teknologi Informasi & Komunikasi'],
    description: 'Astra International membuka posisi Data Scientist untuk membantu transformasi digital grup bisnis otomotif dan finansial terbesar Indonesia melalui analisis data dan machine learning.',
    requirements: [
      'Pendidikan S1/S2 jurusan Statistik, Matematika, atau Ilmu Komputer',
      'Pengalaman minimal 2 tahun sebagai Data Scientist',
      'Menguasai Python dan library ML (scikit-learn, TensorFlow, PyTorch)',
      'Pengalaman dengan SQL dan big data tools',
      'Kemampuan komunikasi insight kepada stakeholder non-teknis',
    ],
    benefits: [
      'Gaji kompetitif + bonus tahunan',
      'BPJS + asuransi swasta',
      'Tunjangan kendaraan',
      'Program pengembangan karir terstruktur',
      'Kesempatan studi lanjut yang didukung perusahaan',
    ],
  },
  {
    id: 'ft-4',
    company: 'Tiket.com',
    position: 'DevOps Engineer',
    location: 'Jakarta',
    salary: 'Rp 15–28 jt/bln',
    tags: ['Teknologi Informasi & Komunikasi'],
    description: 'Tiket.com mencari DevOps Engineer untuk memperkuat infrastruktur cloud dan pipeline CI/CD platform travel terkemuka Indonesia. Kamu akan memastikan sistem berjalan dengan uptime tinggi dan performa optimal.',
    requirements: [
      'Pengalaman minimal 3 tahun sebagai DevOps/SRE Engineer',
      'Menguasai Kubernetes, Docker, dan Terraform',
      'Pengalaman dengan cloud provider (AWS/GCP/Azure)',
      'Familiar dengan monitoring tools (Prometheus, Grafana, ELK)',
      'Memahami CI/CD pipeline (Jenkins, GitLab CI, atau GitHub Actions)',
      'Scripting dengan Bash atau Python',
    ],
    benefits: [
      'Gaji kompetitif',
      'Asuransi kesehatan untuk keluarga',
      'Remote-friendly culture',
      'Budget sertifikasi cloud',
      'Flexible working hours',
    ],
  },
  {
    id: 'ft-5',
    company: 'Mandiri',
    position: 'Business Analyst',
    location: 'Jakarta',
    salary: 'Rp 10–18 jt/bln',
    tags: ['Perbankan & Layanan Finansial', 'Konsultasi & Strategi'],
    description: 'Bank Mandiri membuka posisi Business Analyst untuk mendukung transformasi digital dan pengembangan produk perbankan. Kamu akan menjembatani kebutuhan bisnis dengan solusi teknologi.',
    requirements: [
      'Pendidikan S1 jurusan Ekonomi, Bisnis, atau Teknik',
      'Pengalaman minimal 2 tahun sebagai Business Analyst',
      'Kemampuan analisis data dan pembuatan laporan yang kuat',
      'Familiar dengan metodologi Agile/Scrum',
      'Pengalaman membuat BRD dan user story',
      'Kemampuan komunikasi yang baik dengan stakeholder',
    ],
    benefits: [
      'Gaji pokok + tunjangan jabatan',
      'BPJS Kesehatan dan Ketenagakerjaan',
      'Dana pensiun',
      'Fasilitas pinjaman karyawan',
      'Jenjang karir yang jelas di BUMN',
    ],
  },
  {
    id: 'ft-6',
    company: 'Pertamina',
    position: 'Software Architect',
    location: 'Jakarta',
    salary: 'Rp 25–50 jt/bln',
    tags: ['Teknologi Informasi & Komunikasi', 'Teknik'],
    description: 'Pertamina Digital membuka posisi Software Architect senior untuk memimpin desain arsitektur sistem digital yang mendukung operasional energi nasional. Posisi strategis dengan dampak besar.',
    requirements: [
      'Pengalaman minimal 8 tahun di software development',
      'Minimal 3 tahun pengalaman sebagai Software Architect',
      'Menguasai arsitektur microservices, event-driven, dan cloud-native',
      'Pengalaman dengan enterprise integration patterns',
      'Kemampuan leadership dan mentoring tim teknis',
      'Sertifikasi cloud (AWS/GCP/Azure) menjadi nilai plus',
    ],
    benefits: [
      'Paket kompensasi sangat kompetitif',
      'Asuransi kesehatan premium',
      'Tunjangan perumahan dan kendaraan',
      'Dana pensiun BUMN',
      'Kesempatan memimpin proyek strategis nasional',
    ],
  },
]

export default function FullTimePage() {
  return <JobsPage type="full-time" title="Full Time" jobs={jobs} />
}
