import JobsPage, { Job } from '@/app/components/JobsPage'

const jobs: Job[] = [
  {
    id: 'fl-1',
    company: 'Tokopedia',
    position: 'UI/UX Designer',
    location: 'Jakarta',
    salary: 'Rp 8–15 jt/proyek',
    tags: ['Desain & Arsitektur', 'Teknologi Informasi & Komunikasi'],
    description: 'Kami mencari UI/UX Designer freelance untuk membantu merancang pengalaman pengguna yang intuitif dan menarik pada platform e-commerce kami. Kamu akan berkolaborasi dengan tim produk dan engineering.',
    requirements: [
      'Pengalaman minimal 2 tahun sebagai UI/UX Designer',
      'Mahir menggunakan Figma atau Adobe XD',
      'Memiliki portofolio desain yang kuat',
      'Memahami prinsip user-centered design',
      'Mampu membuat wireframe, prototype, dan design system',
      'Komunikasi yang baik dan responsif',
    ],
    benefits: [
      'Bayaran kompetitif per proyek',
      'Kerja remote, fleksibel waktu',
      'Kesempatan proyek jangka panjang',
      'Feedback dan review dari tim senior',
    ],
  },
  {
    id: 'fl-2',
    company: 'Gojek',
    position: 'Frontend Developer',
    location: 'Remote',
    salary: 'Rp 10–20 jt/proyek',
    tags: ['Teknologi Informasi & Komunikasi'],
    description: 'Gojek membuka kesempatan bagi Frontend Developer freelance untuk membantu pengembangan fitur-fitur baru pada aplikasi super app kami. Proyek bersifat jangka pendek hingga menengah.',
    requirements: [
      'Menguasai React.js atau Vue.js',
      'Pengalaman minimal 2 tahun di frontend development',
      'Familiar dengan TypeScript',
      'Memahami responsive design dan cross-browser compatibility',
      'Pengalaman dengan REST API dan GraphQL',
      'Mampu bekerja mandiri dan memenuhi deadline',
    ],
    benefits: [
      'Rate kompetitif sesuai pengalaman',
      'Full remote, kerja dari mana saja',
      'Akses ke tech stack modern',
      'Potensi kontrak berkelanjutan',
    ],
  },
  {
    id: 'fl-3',
    company: 'Kompas',
    position: 'Content Writer',
    location: 'Jakarta',
    salary: 'Rp 3–6 jt/proyek',
    tags: ['Periklanan, Seni & Media', 'Pemasaran & Komunikasi'],
    description: 'Kompas.com mencari Content Writer freelance untuk menghasilkan artikel berkualitas tinggi di berbagai topik mulai dari berita, lifestyle, teknologi, hingga bisnis.',
    requirements: [
      'Kemampuan menulis yang baik dalam Bahasa Indonesia',
      'Memahami SEO dasar dan penulisan untuk digital',
      'Mampu riset topik secara mandiri',
      'Pengalaman menulis artikel minimal 1 tahun',
      'Deadline-oriented dan teliti',
    ],
    benefits: [
      'Bayaran per artikel yang kompetitif',
      'Fleksibel waktu pengerjaan',
      'Byline di media nasional terkemuka',
      'Kesempatan menjadi kontributor tetap',
    ],
  },
  {
    id: 'fl-4',
    company: 'Shopee',
    position: 'Graphic Designer',
    location: 'Remote',
    salary: 'Rp 5–12 jt/proyek',
    tags: ['Desain & Arsitektur', 'Periklanan, Seni & Media'],
    description: 'Shopee membutuhkan Graphic Designer freelance untuk membuat aset visual kampanye marketing, banner promosi, dan konten media sosial yang menarik dan on-brand.',
    requirements: [
      'Mahir Adobe Photoshop, Illustrator, dan After Effects',
      'Portofolio desain digital yang kuat',
      'Memahami brand guideline dan konsistensi visual',
      'Pengalaman desain untuk e-commerce menjadi nilai plus',
      'Mampu mengerjakan revisi dengan cepat',
    ],
    benefits: [
      'Proyek rutin setiap bulan',
      'Kerja remote penuh',
      'Exposure ke brand e-commerce terbesar di Asia Tenggara',
      'Bayaran tepat waktu',
    ],
  },
  {
    id: 'fl-5',
    company: 'Trans Media',
    position: 'Video Editor',
    location: 'Jakarta',
    salary: 'Rp 4–8 jt/proyek',
    tags: ['Periklanan, Seni & Media'],
    description: 'Trans Media membuka peluang bagi Video Editor freelance untuk mengerjakan konten digital, iklan, dan program pendek untuk platform streaming dan media sosial.',
    requirements: [
      'Mahir Adobe Premiere Pro dan After Effects',
      'Pengalaman editing video minimal 1 tahun',
      'Memiliki sense of storytelling yang kuat',
      'Mampu color grading dan audio mixing dasar',
      'Portofolio video yang beragam',
    ],
    benefits: [
      'Proyek dari media nasional ternama',
      'Bayaran per proyek yang menarik',
      'Fleksibel lokasi kerja',
      'Networking dengan industri media',
    ],
  },
  {
    id: 'fl-6',
    company: 'Unilever',
    position: 'Social Media Specialist',
    location: 'Remote',
    salary: 'Rp 5–10 jt/proyek',
    tags: ['Pemasaran & Komunikasi', 'Periklanan, Seni & Media'],
    description: 'Unilever Indonesia mencari Social Media Specialist freelance untuk mengelola konten dan strategi media sosial brand-brand consumer goods kami di berbagai platform.',
    requirements: [
      'Pengalaman mengelola akun media sosial brand minimal 2 tahun',
      'Memahami algoritma Instagram, TikTok, dan Twitter/X',
      'Kemampuan copywriting yang kuat',
      'Familiar dengan tools analitik media sosial',
      'Kreatif dan up-to-date dengan tren digital',
    ],
    benefits: [
      'Bekerja dengan brand FMCG global',
      'Remote dan fleksibel',
      'Exposure ke strategi marketing kelas dunia',
      'Potensi kontrak jangka panjang',
    ],
  },
]

export default function FreelancePage() {
  return <JobsPage type="freelance" title="Freelance" jobs={jobs} />
}
