import JobsPage, { Job } from '@/app/components/JobsPage'

const jobs: Job[] = [
  {
    id: 'mg-1',
    company: 'Traveloka',
    position: 'Software Engineer Intern',
    location: 'Jakarta',
    salary: 'Rp 2–4 jt/bln',
    tags: ['Teknologi Informasi & Komunikasi'],
    description: 'Traveloka membuka program magang Software Engineer untuk mahasiswa semester 6–8 atau fresh graduate. Kamu akan terlibat langsung dalam pengembangan fitur produk Traveloka yang digunakan jutaan pengguna.',
    requirements: [
      'Mahasiswa aktif jurusan Ilmu Komputer, Teknik Informatika, atau sejenisnya',
      'Menguasai minimal satu bahasa pemrograman (Python, Java, Go, atau Kotlin)',
      'Memahami dasar-dasar struktur data dan algoritma',
      'Familiar dengan Git dan version control',
      'Mampu berkomitmen minimal 3 bulan',
    ],
    benefits: [
      'Uang saku kompetitif',
      'Mentoring dari engineer senior',
      'Sertifikat magang resmi',
      'Peluang konversi ke full-time',
      'Akses ke learning platform internal',
    ],
  },
  {
    id: 'mg-2',
    company: 'Grab',
    position: 'Marketing Intern',
    location: 'Jakarta',
    salary: 'Rp 1,5–3 jt/bln',
    tags: ['Pemasaran & Komunikasi'],
    description: 'Grab Indonesia membuka program magang Marketing untuk mahasiswa yang ingin belajar strategi pemasaran digital di perusahaan teknologi regional terkemuka.',
    requirements: [
      'Mahasiswa aktif jurusan Marketing, Komunikasi, atau Bisnis',
      'Tertarik dengan digital marketing dan growth strategy',
      'Kemampuan analisis data dasar (Excel/Google Sheets)',
      'Kreatif dan memiliki inisiatif tinggi',
      'Bersedia magang minimal 3 bulan',
    ],
    benefits: [
      'Uang saku bulanan',
      'Pengalaman di startup unicorn regional',
      'Mentoring dari marketing manager',
      'Sertifikat dan rekomendasi kerja',
    ],
  },
  {
    id: 'mg-3',
    company: 'OVO',
    position: 'Data Analyst Intern',
    location: 'Jakarta',
    salary: 'Rp 2–3,5 jt/bln',
    tags: ['Teknologi Informasi & Komunikasi', 'Ilmu Pengetahuan & Teknologi'],
    description: 'OVO membuka posisi magang Data Analyst untuk membantu tim dalam menganalisis data transaksi, perilaku pengguna, dan tren bisnis untuk mendukung pengambilan keputusan.',
    requirements: [
      'Mahasiswa jurusan Statistik, Matematika, Ilmu Komputer, atau sejenisnya',
      'Menguasai SQL dan Python/R untuk analisis data',
      'Familiar dengan tools visualisasi data (Tableau, Power BI, atau Looker)',
      'Kemampuan berpikir analitis yang kuat',
      'Mampu berkomitmen 3–6 bulan',
    ],
    benefits: [
      'Uang saku kompetitif',
      'Akses ke data real fintech',
      'Mentoring dari data scientist senior',
      'Sertifikat magang resmi',
      'Peluang full-time setelah magang',
    ],
  },
  {
    id: 'mg-4',
    company: 'Bukalapak',
    position: 'Business Development Intern',
    location: 'Bandung',
    salary: 'Rp 1,5–2,5 jt/bln',
    tags: ['Konsultasi & Strategi', 'Penjualan'],
    description: 'Bukalapak membuka program magang Business Development untuk mahasiswa yang ingin belajar strategi pengembangan bisnis, partnership, dan ekspansi pasar di ekosistem e-commerce.',
    requirements: [
      'Mahasiswa jurusan Bisnis, Manajemen, atau Ekonomi',
      'Kemampuan komunikasi dan negosiasi yang baik',
      'Analitis dan berorientasi pada data',
      'Mampu bekerja dalam tim maupun mandiri',
      'Bersedia ditempatkan di Bandung',
    ],
    benefits: [
      'Uang saku bulanan',
      'Pengalaman di ekosistem startup',
      'Networking dengan profesional bisnis',
      'Sertifikat dan surat rekomendasi',
    ],
  },
  {
    id: 'mg-5',
    company: 'Dana',
    position: 'UI Designer Intern',
    location: 'Jakarta',
    salary: 'Rp 2–3 jt/bln',
    tags: ['Desain & Arsitektur', 'Teknologi Informasi & Komunikasi'],
    description: 'Dana membuka program magang UI Designer untuk mahasiswa desain yang ingin berkontribusi dalam merancang antarmuka aplikasi dompet digital yang digunakan puluhan juta pengguna.',
    requirements: [
      'Mahasiswa jurusan Desain Komunikasi Visual, Desain Produk, atau sejenisnya',
      'Mahir menggunakan Figma',
      'Memiliki portofolio desain UI (minimal 2 proyek)',
      'Memahami prinsip desain mobile-first',
      'Mampu berkomitmen minimal 3 bulan',
    ],
    benefits: [
      'Uang saku bulanan',
      'Mentoring dari senior UI/UX designer',
      'Kontribusi nyata ke produk yang dipakai jutaan orang',
      'Sertifikat magang resmi',
    ],
  },
  {
    id: 'mg-6',
    company: 'Telkom',
    position: 'HR Intern',
    location: 'Bandung',
    salary: 'Rp 1,5–2,5 jt/bln',
    tags: ['Sumber Daya Manusia & Rekrutmen'],
    description: 'Telkom Indonesia membuka program magang HR untuk mahasiswa yang ingin belajar proses rekrutmen, pengembangan SDM, dan administrasi kepegawaian di BUMN telekomunikasi terbesar Indonesia.',
    requirements: [
      'Mahasiswa jurusan Psikologi, Manajemen SDM, atau Administrasi Bisnis',
      'Komunikatif dan memiliki interpersonal skill yang baik',
      'Teliti dalam administrasi dan dokumentasi',
      'Familiar dengan Microsoft Office',
      'Bersedia ditempatkan di Bandung',
    ],
    benefits: [
      'Uang saku bulanan',
      'Pengalaman di BUMN nasional',
      'Sertifikat magang resmi',
      'Networking dengan profesional HR',
      'Peluang rekrutmen jalur khusus',
    ],
  },
]

export default function MagangPage() {
  return <JobsPage type="magang" title="Magang" jobs={jobs} />
}
