import JobsPage, { Job } from '@/app/components/JobsPage'

const jobs: Job[] = [
  {
    id: 'pt-1',
    company: 'Kopi Kenangan',
    position: 'Barista',
    location: 'Jakarta',
    salary: 'Rp 2,5–4 jt/bln',
    tags: ['Perhotelan & Pariwisata', 'Perdagangan & Layanan'],
    description: 'Kopi Kenangan membuka lowongan Barista part-time untuk outlet di area Jakarta. Kamu akan bertanggung jawab menyajikan minuman berkualitas dan memberikan pelayanan terbaik kepada pelanggan.',
    requirements: [
      'Usia minimal 18 tahun',
      'Ramah, energik, dan suka berinteraksi dengan orang',
      'Bersedia bekerja shift (pagi/sore)',
      'Pengalaman barista menjadi nilai plus, tapi tidak wajib',
      'Bersedia ditempatkan di outlet terdekat domisili',
    ],
    benefits: [
      'Gaji pokok + insentif penjualan',
      'Makan dan minum gratis selama shift',
      'Pelatihan barista profesional',
      'Jenjang karir ke posisi full-time',
    ],
  },
  {
    id: 'pt-2',
    company: 'Lazada',
    position: 'Customer Service',
    location: 'Jakarta',
    salary: 'Rp 3–5 jt/bln',
    tags: ['Call Center & Layanan Konsumen'],
    description: 'Lazada Indonesia membuka posisi Customer Service part-time untuk membantu pelanggan melalui chat, email, dan telepon. Cocok untuk mahasiswa atau yang ingin penghasilan tambahan.',
    requirements: [
      'Komunikasi tertulis dan lisan yang baik',
      'Sabar dan mampu menangani komplain dengan profesional',
      'Familiar dengan komputer dan aplikasi chat',
      'Bersedia bekerja 4–5 jam per hari',
      'Pengalaman CS menjadi nilai plus',
    ],
    benefits: [
      'Kerja dari rumah (WFH)',
      'Jadwal fleksibel',
      'Pelatihan customer service',
      'Bonus performa bulanan',
    ],
  },
  {
    id: 'pt-3',
    company: 'BCA',
    position: 'Data Entry',
    location: 'Surabaya',
    salary: 'Rp 2,5–3,5 jt/bln',
    tags: ['Administrasi & Dukungan Perkantoran', 'Perbankan & Layanan Finansial'],
    description: 'BCA membuka posisi Data Entry part-time di kantor cabang Surabaya. Tugas utama meliputi input data nasabah, verifikasi dokumen, dan administrasi umum.',
    requirements: [
      'Minimal lulusan SMA/SMK atau sedang kuliah',
      'Teliti, rapi, dan cepat dalam mengetik',
      'Familiar dengan Microsoft Excel dan Word',
      'Bersedia bekerja 4 jam per hari (pagi)',
      'Domisili Surabaya',
    ],
    benefits: [
      'Pengalaman kerja di perbankan nasional',
      'Lingkungan kerja profesional',
      'Sertifikat pengalaman kerja',
      'Potensi direkrut full-time',
    ],
  },
  {
    id: 'pt-4',
    company: 'Ruangguru',
    position: 'Tutor Matematika',
    location: 'Remote',
    salary: 'Rp 3–6 jt/bln',
    tags: ['Pendidikan & Pelatihan'],
    description: 'Ruangguru mencari Tutor Matematika part-time untuk mengajar siswa SMP dan SMA secara online. Jadwal fleksibel, cocok untuk mahasiswa atau fresh graduate.',
    requirements: [
      'Mahasiswa atau lulusan jurusan Matematika, Teknik, atau sains',
      'IPK minimal 3.2',
      'Mampu menjelaskan konsep dengan cara yang mudah dipahami',
      'Memiliki laptop dan koneksi internet stabil',
      'Bersedia mengajar minimal 10 jam per minggu',
    ],
    benefits: [
      'Bayaran per jam yang kompetitif',
      'Jadwal mengajar fleksibel',
      'Pelatihan pedagogi dari Ruangguru',
      'Sertifikat pengajar resmi',
    ],
  },
  {
    id: 'pt-5',
    company: 'Indomaret',
    position: 'Kasir',
    location: 'Bandung',
    salary: 'Rp 2–3 jt/bln',
    tags: ['Ritel & Produk Konsumen', 'Perdagangan & Layanan'],
    description: 'Indomaret membuka lowongan Kasir part-time di berbagai gerai Bandung. Tugas meliputi melayani transaksi pembayaran, menjaga kebersihan area kasir, dan membantu pelanggan.',
    requirements: [
      'Minimal lulusan SMA/SMK',
      'Jujur, teliti, dan bertanggung jawab',
      'Bersedia bekerja shift',
      'Domisili Bandung dan sekitarnya',
      'Tidak buta warna',
    ],
    benefits: [
      'Gaji pokok + tunjangan shift',
      'BPJS Kesehatan dan Ketenagakerjaan',
      'Diskon belanja karyawan',
      'Peluang promosi ke posisi tetap',
    ],
  },
  {
    id: 'pt-6',
    company: 'Blibli',
    position: 'Admin Online Shop',
    location: 'Remote',
    salary: 'Rp 2,5–4 jt/bln',
    tags: ['Administrasi & Dukungan Perkantoran', 'Penjualan'],
    description: 'Blibli membuka posisi Admin Online Shop part-time untuk membantu pengelolaan toko, upload produk, membalas chat pembeli, dan memproses pesanan.',
    requirements: [
      'Familiar dengan platform marketplace (Blibli, Tokopedia, Shopee)',
      'Kemampuan komunikasi tertulis yang baik',
      'Teliti dalam pengelolaan stok dan pesanan',
      'Bersedia online minimal 5 jam per hari',
      'Memiliki laptop/PC dan internet stabil',
    ],
    benefits: [
      'Kerja dari rumah penuh',
      'Jadwal fleksibel',
      'Bonus dari target penjualan',
      'Pengalaman di e-commerce terkemuka',
    ],
  },
]

export default function PartTimePage() {
  return <JobsPage type="part-time" title="Part Time" jobs={jobs} />
}
